apiVersion: v1
kind: Namespace
metadata:
  name: k2a-monitoring
  labels:
    name: k2a-monitoring
    purpose: cluster-monitoring
    security.openshift.io/scc.podSecurityLabelSync: "false"
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/warn: "restricted"
  annotations:
    openshift.io/description: "Namespace para K2A Enterprise Monitoring"
    openshift.io/display-name: "K2A Monitoring"