apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: k2a-monitoring-staging

namespace: k2a-monitoring-staging

resources:
- ../../base

namePrefix: staging-

commonLabels:
  environment: staging
  
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: k2a-monitoring-staging
  target:
    kind: Namespace
    name: k2a-monitoring

- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: k2a-monitoring-agent

- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: staging
  target:
    kind: Deployment
    name: k2a-monitoring-agent

images:
- name: quay.io/k2a/monitoring-agent
  newTag: v1.0.0-rc