{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kmcp-servers.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.rbac.clusterRoleBinding.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.namespace }}-monitoring-view
  labels:
    {{- include "kmcp-servers.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccount.name }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRoleBinding.clusterRole }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
