{{- if .Values.monitoring.serviceMonitor.enabled }}
{{- range $key, $server := .Values.servers }}
{{- if $server.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $server.name }}-monitor
  namespace: {{ $.Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ $server.name }}
    {{- with $.Values.common.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $server.name }}
  endpoints:
    - port: http
      path: {{ $.Values.monitoring.serviceMonitor.path | default "/metrics" }}
      interval: {{ $.Values.monitoring.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ $.Values.monitoring.serviceMonitor.scrapeTimeout | default "10s" }}
  namespaceSelector:
    matchNames:
      - {{ $.Values.global.namespace }}
{{- end }}
{{- end }}
{{- end }}
